import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import codeReferenceSidebar from './code-reference-sidebar';

const sidebars: SidebarsConfig = {
  startupSidebar: ['startup/setup', 'startup/dataset', 'startup/first-training', 'startup/results'],
  userGuideSidebar: [
    'user-guide/index',
    'user-guide/workflow',
    'user-guide/configuration',
    'user-guide/training',
    'user-guide/checkpoints',
    'user-guide/outputs',
    'user-guide/circuit',
    {
      type: 'category',
      label: 'モデル・データセットの追加',
      link: {type: 'doc', id: 'user-guide/extension'},
      items: ['user-guide/models', 'user-guide/datasets'],
    },
    {
      type: 'category',
      label: 'logicNNライブラリ',
      link: {type: 'doc', id: 'user-guide/logicnn-library/index'},
      items: [
        'user-guide/logicnn-library/basics',
        'user-guide/logicnn-library/algorithms',
        'user-guide/logicnn-library/connections',
        'user-guide/logicnn-library/classes',
        'user-guide/logicnn-library/reading-code',
        'user-guide/core-library',
        'user-guide/logicnn-library/circuits',
        'user-guide/logicnn-library/papers',
      ],
    },
    'user-guide/troubleshooting',
  ],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],
  codeReferenceSidebar,
  specificationsSidebar: [{type: 'autogenerated', dirName: 'specifications'}],
};

export default sidebars;
